### PR TITLE
Update library for Hilo3d and glTF Loader

### PR DESCRIPTION
**Pull request by 06wj**
* Add [KHR_techniques_webgl](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_techniques_webgl) support.
* Add [KHR_lights_punctual](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual) support

### CODE REVIEW

**Comment by cx20** [comment]
I am always grateful for your help.

**Comment by cx20** [comment]
@06wj Please tell me if you have samples to try this fix. I would like to try it.

**Comment by 06wj** [comment]
@cx20 
* KHR_techniques_webgl
    * [demo](https://cx20.github.io/gltf-test/examples/Hilo3d/index.html?url=https://hiloteam.github.io/Hilo3d/examples/models/SampleTechniques/SampleTechniques.gltf&scale=1&type=glTF)
    * [model](https://github.com/hiloteam/Hilo3d/tree/master/examples/models/SampleTechniques)
* KHR_lights_punctual
    * [demo](https://cx20.github.io/gltf-test/examples/Hilo3d/index.html?url=https://raw.githubusercontent.com/mrdoob/three.js/dev/examples/models/gltf/Monster/glTF-lights/Monster.gltf&scale=0.04) 
    * [model](https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf/Monster/glTF-lights)

**Comment by cx20** [comment]
@06wj Thank you for telling me the sample.

In Three.js Monster.gltf seems to animate. Should this model be animated?
https://cx20.github.io/gltf-test/examples/threejs/index.html?url=https://raw.githubusercontent.com/mrdoob/three.js/dev/examples/models/gltf/Monster/glTF-lights/Monster.gltf&scale=0.04

**Comment by 06wj** [comment]
@cx20 

> Implementation Note: glTF 2.0 does not specifically define how an animation will be used when imported but, as a best practice, it is recommended that each animation is self contained as an action. For example, "Walk" and "Run" animations might each contain multiple channels targeting a model's various bones. The client implementation may choose when to play any of the available animations.

The animation of this model is not in the recommended format, so the playback is not correct.

**Comment by cx20** [comment]
In the glTF-Sample-Models repository, [Monster.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Monster) seems to play animation. Is this the recommended format? I do not understand the difference well.

https://cx20.github.io/gltf-test/examples/Hilo3d/?url=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Monster/glTF/Monster.gltf&scale=0.04

**Comment by 06wj** [comment]
@cx20 

The animation data is organized differently, probably writing the structure. The first is the recommended way. Each item in the ```animations``` array represents an action, and all the node information is contained in it. The second is not recommended, the entire ```animations``` represent an action.
```
animations:[
       {channels:[node0, node1, node2]} // run anim,
       {channels:[node0, node1, node2]} // jump anim
]
```

```
animations:[
       {channels:[node0]}, // node0 run anim
       {channels:[node1]}, // node1 run anim
       {channels:[node2]} // node2 run anim
]
```

**Comment by cx20** [comment]
@06wj Thank you for explaining.
I understood that [Monster.gltf](https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf/Monster/glTF-lights) corresponding to KHR_lights_punctual in the three.js repository  is not in the recommended animation format,

**Pull request merged**
