### PR TITLE
update Hilo3d 1.5.7 version for fixing Normal-Tangent Test bug

### PR DESCRIPTION
**Pull request by 06wj**
Hello, I update Hilo3d 1.5.7 version for fixing Normal-Tangent Test bug.
Here is the [Normal-Tangent Test](https://06wj.github.io/gltf-test/examples/Hilo3d/index.html?category=tutorialModels&model=NormalTangentTest&scale=1&type=glTF-Embedded&v=1.5.7)

### CODE REVIEW

**Comment by cx20** [comment]
@06wj I confirmed the fix. Your status will be all green. congratulations.

**Comment by 06wj** [comment]
@cx20 I add skybox and loading for Hilo3d's demo in this pr.

**Comment by cx20** [comment]
Oops! I made a mistake, Close instead of Merge.

**Comment by cx20** [comment]
@06wj Merged. I think that I will be fine this time.
https://cx20.github.io/gltf-test/examples/Hilo3d/index.html?category=tutorialModels&model=NormalTangentTest&scale=1&type=glTF
image

**Comment by 06wj** [comment]
Thanks.

**Pull request merged**
