### PR TITLE
Fixed corrupted hdr image file

### PR DESCRIPTION
**Pull request by cx20**

### CODE REVIEW

**Comment by emackey** [comment]
@cx20 If you're having problems with corrupted HDR files on Windows, it may be because they have a nearly plain-text header, and Git mistakes them for fully plain-text files.  This causes linefeed conversion to happen on Windows, and corrupts the files.

The fix is to include a `.gitattributes` file [like the sample viewer one](https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/2e6f9f1cfef04239cc8c8c403a5c49a242b1dc3f/.gitattributes#L7-L11) that marks these files specifically as binary data, protecting them from linefeed conversion.

**Comment by cx20** [comment]
@emackey Thanks for the advice. I think the cause of the problem is exactly what you pointed out. 
I've decided to add `.gitattributes` to this repository.

**Comment by cx20** [comment]
BTW, I was a little concerned that the `.hdr` file I was supposed to have added with this PR wasn't included, but I figured out why.
Perhaps the problem with the line endings only occurred on my local Windows PC and on GitHub it was still in LF, not CLRF, so there was no need to replace the `.hdr` file.

**Comment by emackey** [comment]
Try this.  I'm not 100% sure but I think this will fix it.

1. Move the "good" HDR file to a different folder for safe keeping.
2. Git thinks the file was deleted, revert that to bring the file back.  The file Git gives you get will be corrupt.
3. Overwrite the corrupt one with a new copy of the original good one.
4. Git should finally realize it changed, and be willing to commit this change as a new "good" version of the file.

**Comment by emackey** [comment]
BTW, Pisa.hdr looks good in Gimp, but Papermill appears all black and may be corrupt.

**Comment by cx20** [comment]
Hmmm, something is definitely wrong. However, it seems that [papermill.hdr](https://github.com/cx20/gltf-test/blob/master/textures/hdr/papermill.hdr) can be viewed in the [OpenHDR Online Image Viewer](https://viewer.openhdr.org/).

image

I remembered how I created that HDR file. The steps are as follows.

1. download https://github.com/KhronosGroup/glTF-Sample-Environments/blob/master/papermill.hdr
2. download https://github.com/google/filament/tree/main/tools/cmgen (This tool is included in [filament-xxxx-windows.tgz](https://github.com/google/filament/releases/download/v1.9.8/filament-v1.9.8-windows.tgz))
3. Uses cmgen to resize the texture
```
cmgen.exe -x . --type=equirect --format=hdr --size=512 --no-mirror papermill.hdr
```

I'm going to have to try the latest version of cmgen.

**Comment by cx20** [comment]
I have tried viewing HDR files with some tools.
These tools don't turn black, so I feel like there's something wrong with GIMP. (Maybe not.)

HDR + WCG Image Viewer
https://www.microsoft.com/en-us/p/hdr-wcg-image-viewer/9pgn3nwpbwl9
image

Picturenaut 3
http://www.hdrlabs.com/picturenaut/
image

**Pull request merged**
