### PR TITLE
Update PlayCanvas v1.51.0 to v1.51.4

### PR DESCRIPTION
**Pull request by cx20**

### CODE REVIEW

**Comment by willeastcott** [comment]
Wouldn't it be easier to use the NPM module? 😄

**Comment by cx20** [comment]
@willeastcott Thanks for the advice.
Unfortunately, I may be doing simple things the hard way due to lack of understanding of the rudiments.
If you don't mind, could you send me a PR with your suggestions for improvement?

**Comment by cx20** [comment]
I don't understand how to use PlayCanvas as an `NPM module`.
Do you mean to refer to the following URL?
https://unpkg.com/playcanvas@1.51.4/build/playcanvas.js

**Comment by willeastcott** [comment]
So to use the NPM module, you need to consider a builder/bundler like Webpack or Rollup. Here's a very basic template that builds a PlayCanvas app with Webpack using the NPM module:

https://github.com/playcanvas/playcanvas-webpack

Then, to upgrade the engine version, you simply need to bump the `playcanvas` version number in the `package.json` of you project.

**Comment by cx20** [comment]
Thank you for telling me how to use it. I will try it.

**Pull request merged**
